#! /bin/sh

if [[ "$1" == "play" ]]
then
  echo "** podman-sim $*"
fi


if [[ "$1" == "pod" && "$2" == "ps" ]]
then
  echo "98a01861eea4,test"
  echo "3b1d8a859f27,twocontainers"
  # echo "68d18ce990f,podman-blog"
  echo "b6d743f98ba3,flask-app"
fi

if [[ "$1" == "pod" && "$2" == "restart" ]]
then
  echo "Restarted Pod: $3" 
fi


if [[ "$1" == "pod" && "$2" == "rm" ]]
then
  echo "Removed Pod: $3" 
fi


